#!/usr/bin/env python3
"""
make_numbers.py -- generates manuscript/numbers.tex and manuscript/tables/*.tex.

Every quantitative statement in the manuscript is written as a LaTeX macro defined
here from results.json and the result CSVs. No number is typed into the manuscript
body by hand, so the text cannot drift away from the computation: re-running
run_case_study.py and then this script updates the paper automatically.

Usage:  python make_numbers.py [--results ../results] [--out ../manuscript]

Author: Saptadeep Biswas
License: MIT
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import re

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ssr_mcda as S  # noqa: E402
from ssr_mcda.data import CASES, REVEALED_PREFERENCES, SECTOR_DEF  # noqa: E402

POST = S.POSTURE_CODES
CRIT = S.CRITERION_CODES
POST_DESC = dict(S.POSTURES)
CRIT_INFO = {c: (n, s) for c, n, s in S.CRITERIA}
CASE_TAG = {"USA": "Usa", "IND": "Ind"}
ROMAN = {0: "Zero", 1: "One", 2: "Two", 3: "Three", 4: "Four", 5: "Five",
         6: "Six", 7: "Seven", 8: "Eight", 9: "Nine"}


def esc(s: str) -> str:
    return (s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
             .replace("#", r"\#"))


def macro(name: str, value) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def alpha(code: str) -> str:
    """A1 -> Aone, C3 -> Cthree, so macro names stay letters-only."""
    return code[0] + ROMAN[int(code[1:])].lower()


# ==========================================================================
def build_numbers(results: str) -> str:
    d = json.load(open(os.path.join(results, "results.json")))
    out = ["% Auto-generated by make_numbers.py -- DO NOT EDIT BY HAND\n",
           f"% generated {d['generated_utc']}\n\n"]

    out.append(macro("ssrversion", d["package_version"]))
    out.append(macro("mcdraws", f"{d['monte_carlo_draws']:,}".replace(",", "\\,")))
    out.append(macro("epsdefault", f"{d['epsilon']:.2f}"))
    out.append(macro("nposture", len(POST)))
    out.append(macro("ncriteria", len(CRIT)))
    out.append(macro("nsector", len(SECTOR_DEF)))
    out.append(macro("nmoebius", len(CRIT) + len(CRIT) * (len(CRIT) - 1) // 2))
    out.append(macro("nmonotone", f"{len(CRIT) * 2 ** (len(CRIT) - 1):,}".replace(",", "\\,")))
    # number of executable property tests, counted from the test file itself
    tf = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tests", "test_ssr_mcda.py")
    ntests = sum(1 for ln in open(tf) if ln.startswith("def test_"))
    out.append(macro("ntests", ntests))
    out.append("\n")

    for case, c in d["cases"].items():
        T = CASE_TAG[case]
        out.append(f"% ---- case {case} ----\n")
        out.append(macro(f"rec{T}", c["recommended"]))
        out.append(macro(f"rec{T}Desc", esc(POST_DESC[c["recommended"]])))
        out.append(macro(f"norigin{T}", len(c["origins"]) - 1))
        out.append(macro(f"radL{T}", f"{c['stability_radius_l1']:.4f}"))
        out.append(macro(f"radInf{T}", f"{c['stability_radius_linf']:.4f}"))
        out.append(macro(f"radChal{T}", c["stability_challenger"]))
        out.append(macro(f"orness{T}", f"{c['orness']:.3f}"))
        out.append(macro(f"marichalH{T}", f"{c.get('marichal_entropy', float('nan')):.3f}"))
        out.append(macro(f"shannonH{T}", f"{c.get('shapley_entropy', float('nan')):.3f}"))
        out.append(macro(f"minShapley{T}", f"{c.get('min_shapley', 0):g}"))
        # Marichal-Roubens comparator
        mr = c.get("marichal_roubens", {})
        out.append(macro(f"mrSep{T}", f"{mr.get('separation', float('nan')):.4f}"))
        out.append(macro(f"mrDist{T}", f"{mr.get('phi_l1_distance_from_cci', float('nan')):.3f}"))
        out.append(macro(f"mrTau{T}", f"{mr.get('kendall_tau_vs_ssr', float('nan')):.2f}"))
        # preference resampling
        pr = c.get("preference_resampling", {})
        out.append(macro(f"looTau{T}", f"{pr.get('leave_one_out_min_tau', float('nan')):.2f}"))
        surv = pr.get("criteria_exceeding_permutation_null", [])
        out.append(macro(f"nullSurvive{T}",
                         (", ".join(surv) if surv else "none") +
                         (f" ({len(surv)})" if surv else "")))
        out.append(macro(f"nullCount{T}", len(surv)))
        out.append(macro(f"mcPrefViol{T}",
                         c.get("monte_carlo", {}).get("draws_with_preference_violation", 0)))
        out.append(macro(f"cciRounds{T}", c["cci"]["rounds"]))
        out.append(macro(f"cciCuts{T}", c["cci"]["cuts"]))
        out.append(macro(f"cciObj{T}", f"{c['cci']['objective']:.4f}"))
        out.append(macro(f"cciViol{T}", f"{c['cci']['monotonicity_violation']:.1e}"
                                        .replace("e-", r"\times 10^{-").replace("+", "") + "}"))
        out.append(macro(f"bwmXi{T}", f"{c['bwm_consistency_xi']:.4f}"))
        out.append(macro(f"npref{T}", len(c["revealed_preferences"])))
        # is the recommendation zero-regret over the whole admissible capacity set?
        zr = c["max_regret"][c["recommended"]] <= 1e-9
        out.append(macro(f"zeroRegret{T}", "yes" if zr else "no"))
        out.append(macro(f"prefViol{T}", c["cci"].get("preference_violations", 0)))
        out.append(macro(f"mcvalid{T}", f"{c['monte_carlo']['n_valid']:,}".replace(",", "\\,")))
        rr = c["rank_reversal"]
        out.append(macro(f"rrStable{T}", f"{100*rr['recommendation_stable_share']:.0f}"))
        out.append(macro(f"rrOrder{T}", f"{100*rr['choquet_order_preserved_share']:.0f}"))
        out.append(macro(f"rrProbes{T}", rr["probes"]))

        for p in POST:
            a = alpha(p)
            out.append(macro(f"score{T}{a}", f"{c['choquet_scores'][p]:.4f}"))
            out.append(macro(f"regret{T}{a}", f"{c['max_regret'][p]:.4f}"))
            out.append(macro(f"rank{T}{a}", c["mcr_rank"][p]))
            out.append(macro(f"mcone{T}{a}", f"{100*c['monte_carlo']['rank1_frequency'][p]:.1f}"))
            out.append(macro(f"mcmean{T}{a}", f"{c['monte_carlo']['mean_rank'][p]:.2f}"))
            out.append(macro(f"smaa{T}{a}", f"{100*c['smaa_rank1_acceptability'][p]:.1f}"))
        for cr in CRIT:
            a = alpha(cr)
            out.append(macro(f"phi{T}{a}", f"{c['shapley_importance'][cr]:.3f}"))
            out.append(macro(f"phigame{T}{a}", f"{c['shapley_of_game'][cr]:+.3f}"))
        # most and least important criteria
        phis = c["shapley_importance"]
        top = max(phis, key=phis.get)
        bot = min(phis, key=phis.get)
        out.append(macro(f"phiTop{T}", top))
        out.append(macro(f"phiTopName{T}", esc(CRIT_INFO[top][0]).lower()))
        out.append(macro(f"phiTopVal{T}", f"{phis[top]:.3f}"))
        out.append(macro(f"phiBot{T}", bot))
        out.append(macro(f"phiBotName{T}", esc(CRIT_INFO[bot][0]).lower()))
        # agreement with benchmarks
        kt = c["kendall_tau_vs_benchmarks"]
        out.append(macro(f"ktMin{T}", f"{min(kt.values()):.2f}"))
        out.append(macro(f"ktMax{T}", f"{max(kt.values()):.2f}"))
        out.append(macro(f"ktMean{T}", f"{np.mean(list(kt.values())):.2f}"))
        out.append("\n")

    # cross-case
    us, ind = d["cases"]["USA"], d["cases"]["IND"]
    out.append(macro("sameRec", "yes" if us["recommended"] == ind["recommended"] else "no"))
    out.append("\n")
    return "".join(out)


# ==========================================================================
_MATH = re.compile(r"(\$[^$]*\$)")


def _escape_outside_math(text: str) -> str:
    """Escape LaTeX specials in `text` WITHOUT touching anything inside $...$.

    pandas' own `escape=True` escapes indiscriminately, which turns a perfectly good
    `$\\sum_k w_k$` into the literal string `\\$\\textbackslash sum\\_k w\\_k\\$` -- the
    formula then appears in the PDF as source code rather than as mathematics. Since
    several of these tables are mostly mathematics, we escape the prose ourselves and
    hand pandas `escape=False`.
    """
    if not isinstance(text, str):
        return text
    out = []
    for part in _MATH.split(text):
        if part.startswith("$") and part.endswith("$"):
            out.append(part)                      # mathematics: leave exactly as written
        else:
            # Two deliberate omissions. Backslashes are NOT escaped, because the prose
            # in these tables legitimately contains LaTeX accents such as G\"urler and
            # Labb\'e. '~' is NOT escaped either: in these tables it is always a
            # non-breaking space before a cross-reference, never a literal tilde.
            for ch, esc in (("&", r"\&"), ("%", r"\%"), ("#", r"\#"), ("_", r"\_")):
                part = part.replace(ch, esc)
            out.append(part)
    return "".join(out)


def tex_table(df: pd.DataFrame, caption: str, label: str, align: str,
              note: str = "", index: bool = True, float_fmt: str = "%.3f",
              small: bool = True, stretch: float | None = None,
              bottom_pad: str | None = None) -> str:
    """Emit a booktabs-free, \\hline-ruled table.

    ``bottom_pad`` inserts extra vertical space between the final data row and
    the closing rule, e.g. "4pt".  It is needed whenever the last row carries a
    \\displaystyle operator: \\arraystretch scales the nominal row height but a
    double summation descends further than that, and its lower limit would
    otherwise print on top of the rule.
    """
    df = df.copy()
    df = df.map(_escape_outside_math) if hasattr(df, "map") else df.applymap(_escape_outside_math)
    df.columns = [_escape_outside_math(c) for c in df.columns]
    idx_name = None
    if index:
        # The header cell above the row labels must carry the index name, otherwise
        # it reads as if the column headings were shifted one cell to the left.
        # pandas puts a named index on a SECOND header row of empty cells, which
        # wastes a line and looks like a defect, so the name is stripped here and
        # spliced into the first cell of the single header row below.
        idx_name = df.index.name
        df.index = pd.Index([_escape_outside_math(i) for i in df.index], name=None)
        if idx_name:
            idx_name = _escape_outside_math(idx_name)
    body = df.to_latex(index=index, escape=False, float_format=lambda x: float_fmt % x,
                       column_format=align, bold_rows=False)
    body = body.replace("\\toprule", "\\hline").replace("\\midrule", "\\hline") \
               .replace("\\bottomrule", "\\hline")
    if idx_name:
        body = body.replace("\\hline\n & ", "\\hline\n" + idx_name + " & ", 1)
    if bottom_pad:
        # the last "\\\n" before the closing rule is the end of the final data row
        i = body.rfind("\\\\\n\\hline")
        if i >= 0:
            body = body[:i] + f"\\\\[{bottom_pad}]\n\\hline" + body[i + len("\\\\\n\\hline"):]
    sz = "\\small\n" if small else ""
    if stretch:
        sz += f"\\renewcommand{{\\arraystretch}}{{{stretch}}}\n"
    nt = f"\\\\[2pt]\n\\begin{{minipage}}{{\\linewidth}}\\footnotesize {note}\\end{{minipage}}\n" if note else ""
    return (f"\\begin{{table}}[!htbp]\n\\centering\n{sz}"
            f"\\caption{{{caption}}}\n\\label{{{label}}}\n{body}{nt}\\end{{table}}\n")


def build_tables(results: str, out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)
    d = json.load(open(os.path.join(results, "results.json")))

    # T1 criteria definitions
    #
    # Each definition is set in \displaystyle so the summation limits sit above and
    # below the operator rather than beside it; in a table column the default
    # text-style rendering compresses \sum_k \sum_p into an illegible cluster.
    defs = [
        r"\displaystyle\sum_k w_k \sum_p x^{*}_{kp}\, c_{kp}\,(1+\tau_{kp})",
        r"\displaystyle\sum_k w_k \sum_p x^{*}_{kp}\, c_{kp}\,\tau_{kp}",
        r"\displaystyle\sum_k w_k\, x^{*}_{k,\mathrm{DOM}}",
        r"\displaystyle\sum_k w_k \Bigl(1-\sum_p \bigl(x^{*}_{kp}\bigr)^{2}\Bigr)",
        r"\displaystyle\sum_k w_k \sum_p x^{*}_{kp}\, g_p",
        r"\displaystyle\tfrac{1}{5}\sum_k w_k \sum_p x^{*}_{kp}\, \mathrm{LPI}_p",
        # exports are TOTAL bilateral, not sector-specific: E_p, not E_{kp}
        r"\displaystyle\sum_k w_k \Bigl(\sum_p r^{*}_p E_p \Big/ \sum_p E_p\Bigr)",
        r"\displaystyle\sum_k w_k\, \ell_k\, x^{*}_{k,\mathrm{DOM}}",
        r"\displaystyle 10^{-4}\sum_k w_k \sum_p x^{*}_{kp}\, d_p",
    ]
    rows = [{"Code": c, "Criterion": n,
             "Direction": "benefit" if sense == "benefit" else "cost",
             "Definition at the equilibrium": f"${defn}$"}
            for (c, n, sense), defn in zip(S.CRITERIA, defs)]
    t1 = pd.DataFrame(rows)
    open(os.path.join(out_dir, "tab_criteria.tex"), "w").write(
        tex_table(t1, "Evaluation criteria. Every criterion is a functional of the unique "
                      "lower-level response of the Layer-I model, not an independently "
                      "elicited score.",
                  "tab:criteria", "clll",
                  note=r"$w_k$ is the import-value share of sector $k$; $x^{*}$ and $r^{*}$ "
                       r"are the equilibrium sourcing and retaliation vectors; $g_p$ is "
                       r"geopolitical distance and $d_p$ great-circle distance from the focal "
                       r"capital; $\mathrm{LPI}_p$ is the Logistics Performance Index score "
                       r"and $\ell_k$ sector labour intensity. $E_p$ denotes \emph{total} "
                       r"bilateral exports to origin $p$: WITS does not serve export values by "
                       r"product group for these reporters, so C7 measures the share of total "
                       r"exports facing new duties, aggregated with sector weights.",
                  index=False, stretch=1.9, bottom_pad="5pt"))

    # T2 postures
    t2 = pd.DataFrame([{"Code": c, "Posture": desc.split(" (")[0],
                        "Instrument applied to the observed tariff vector": rule}
                       for (c, desc), rule in zip(S.POSTURES, [
                           r"$\tau_p = \tau^{0}_{p}$ for every origin",
                           r"$\tau_p = 0$ for every foreign origin",
                           r"$\tau_p = \tau^{0}_{p} + u$ for every foreign origin",
                           r"$\tau_q = \tau^{0}_{q} + t$ for the dominant rival $q$; "
                           r"$\tau_p = \tau^{0}_{p}$ otherwise",
                           r"$\tau_p = 0$ if $d_p \le \bar{d}$, else $\tau_p = \tau^{0}_{p} + u$",
                           r"$\tau_p = 0$ if $g_p \le \bar{g}$, else $\tau_p = \tau^{0}_{p} + u$",
                           r"$\tau_p = \tau^{0}_{p} + u$, and $c_{\mathrm{DOM}} \mapsto (1-\sigma)\,c_{\mathrm{DOM}}$"])])
    open(os.path.join(out_dir, "tab_postures.tex"), "w").write(
        tex_table(t2, "Tariff-policy postures. Each posture is a rule that maps the observed "
                      "applied-tariff vector into a counterfactual, so no counterfactual tariff "
                      "level is invented.",
                  "tab:postures", "cll",
                  note=r"$u$ is the uniform tariff increment, $t$ the discriminatory increment, "
                       r"$\bar{d}$ the proximity threshold, $\bar{g}$ the alignment threshold and "
                       r"$\sigma$ the domestic cost subsidy; $q$ denotes the origin with the "
                       r"largest observed import share. Every one of these magnitudes is a "
                       r"modelling choice, not an observation, and each is swept over the range "
                       r"given in Table~\ref{tab:params}.",
                  index=False, stretch=1.35))

    # T3 parameters
    # Reference values are carried as STRINGS, not floats, so that each is printed at
    # its own natural precision: a float column formatter would render the margin
    # 0.001 as "0.00" and the threshold 5000 as "5000.000".
    spec = [("$\\rho$", "sourcing convexity (capacity friction)", "0.60", "0.30--1.20"),
            ("$\\lambda$", "weight on geopolitical risk in landed cost", "0.35", "0.10--0.70"),
            ("$\\beta$", "curvature of a partner's welfare cost of retaliating", "1.20", "0.60--2.00"),
            ("$\\gamma$", "fixed escalation cost of retaliating", "0.02", "0.00--0.06"),
            ("$\\theta_0$", "political return to retaliation", "1.00", "0.50--1.50"),
            ("$\\delta_{\\mathrm{DOM}}$", "baseline domestic sourcing share (calibration)", "0.35", "0.15--0.65"),
            ("$\\sigma$", "domestic cost subsidy under $A_7$", "0.15", "0.05--0.30"),
            ("$u$", "uniform tariff increment", "0.10", "0.05--0.20"),
            ("$t$", "discriminatory tariff increment", "0.25", "0.10--0.45"),
            ("$\\bar g$", "alignment threshold for the friendshoring club", "0.80", "0.60--0.95"),
            ("$\\bar{d}$", "proximity threshold, km", "5000", "3000--8000"),
            ("$\\underline{c}$", r"positivity floor pinning the calibration multiplier in~\eqref{eq:calib}", "0.05", "fixed"),
            ("$\\underline{\\varphi}$", r"minimum representativity in~\eqref{eq:cci}", "0.02", "fixed"),
            ("$\\varsigma$", r"representability margin in~\eqref{eq:cci}", "0.001", "fixed"),
            ("$\\varepsilon$", r"capacity uncertainty radius in~\eqref{eq:uncertainty}", "0.05", r"0--0.30, see Fig.~\ref{fig:epsilon}")]
    # the reference value is formatted as TEXT so that a genuinely small parameter
    # such as delta = 0.001 is not rounded to 0.00 by a two-decimal float format
    t3 = pd.DataFrame([{"Symbol": s, "Interpretation": i,
                        "Reference value": v if isinstance(v, str) else f"{v:g}",
                        "Uncertainty range": r} for s, i, v, r in spec])
    open(os.path.join(out_dir, "tab_params.tex"), "w").write(
        tex_table(t3, "Parameters of the framework. The first eleven are behavioural and are swept "
                      "jointly in the Monte-Carlo experiment and singly in the one-at-a-time "
                      "analysis; the next three are numerical devices held fixed; the last, the "
                      "uncertainty radius, is a reporting choice and is swept separately. The "
                      "table lists every non-observed input in one place.",
                  "tab:params", "clrl", index=False, stretch=1.15))

    # T4/T5 performance matrices, T6 capacity, T7 MCR, T8 benchmarks
    digest = json.load(open(os.path.join(results, "results.json")))
    crit_legend = "; ".join(f"{c} {n.lower()}" for c, n, _ in S.CRITERIA)
    post_legend = "; ".join(f"{c} {d.split(' (')[0].lower()}" for c, d in S.POSTURES)

    for case in CASES:
        nm = "the United States" if case == "USA" else "India"
        d_ = digest["cases"][case]

        # ---- normalised performance matrix ----------------------------------
        # The index carries the posture code, so it needs a header of its own;
        # without one the column headings sit one cell to the left of their data.
        Z = pd.read_csv(os.path.join(results, f"performance_norm_{case}.csv")).set_index("posture")
        Z.columns = CRIT
        Z.index = [f"$A_{p[1]}$" for p in Z.index]
        Z.index.name = "Posture"
        open(os.path.join(out_dir, f"tab_perf_{case}.tex"), "w").write(
            tex_table(Z, f"Normalised equilibrium performance matrix $Z$ for {nm}. "
                         f"Values are benefit-oriented, so higher is better on every "
                         f"criterion, and lie in $[0,1]$.",
                      f"tab:perf{case}", "l" + "r" * len(CRIT), float_fmt="%.3f",
                      note="Criteria: " + crit_legend + ". Postures: " + post_legend + "."))

        # ---- identified capacity --------------------------------------------
        cap = pd.read_csv(os.path.join(results, f"capacity_{case}.csv")).set_index("criterion")
        cap = cap[["name", "sense", "shapley_of_game", "shapley_importance", "moebius_singleton"]]
        # The Shapley value of the raw game is the one quantity in the paper that can
        # be negative, and a bare "-0.419" in text mode sets a hyphen, not a minus.
        # Render that column in math mode; the other two are non-negative by
        # construction and are left to the float formatter.
        cap["shapley_of_game"] = [f"${v:.3f}$" for v in cap["shapley_of_game"]]
        cap.columns = ["Criterion", "Direction",
                       r"$\varphi_i(v)$", r"$\varphi_i(\mu^{\star})$", r"$m_i$"]
        cap.index.name = "Code"
        open(os.path.join(out_dir, f"tab_capacity_{case}.tex"), "w").write(
            tex_table(cap, f"Criterion importance for {nm}: the Shapley value of the "
                           f"discrimination game and of the identified 2-additive capacity.",
                      # index + 2 text columns + 3 numeric columns
                      f"tab:cap{case}", "l" + "ll" + "rrr",
                      note=r"$\varphi_i(v)$ is the Shapley value of the raw discrimination "
                           r"game, which need not be a capacity and may therefore be negative; "
                           r"$\varphi_i(\mu^{\star})$ is the importance index of its projection "
                           r"onto the 2-additive capacity polytope, which is non-negative and "
                           r"sums to one; $m_i$ is the corresponding M\"obius singleton "
                           r"coefficient. Section~\ref{sec:resampling} reports how much of this "
                           r"vector a preference sample of this size actually resolves."))

        # ---- Choquet score and minimax regret -------------------------------
        m = pd.read_csv(os.path.join(results, f"mcr_{case}.csv")).set_index("posture")
        m = m[["choquet_score", "score_rank", "max_regret", "mcr_rank", "binding_adversary"]]
        # an alternative with zero regret has no binding adversary; print an en-dash
        # rather than letting pandas render the empty cell as the string "NaN"
        m["binding_adversary"] = [
            f"$A_{str(x)[1]}$" if isinstance(x, str) and x.startswith("A") else "---"
            for x in m["binding_adversary"]
        ]
        has_dash = "---" in list(m["binding_adversary"])
        m.columns = [r"$C_{\mu^{\star}}(z_a)$", "score rank", r"$R(a)$", "MCR rank",
                     "binding adversary"]
        m.index = [f"$A_{p[1]}$" for p in m.index]
        m.index.name = "Posture"
        rec = d_["recommended"]
        rec_regret = d_["max_regret"][rec]
        # the note must state what the numbers actually show: the recommendation is
        # zero-regret for the United States but NOT for India
        if rec_regret <= 1e-9:
            verdict = (f"the recommendation $A_{rec[1]}$ attains zero regret, so by "
                       r"Theorem~\ref{thm:mcr}(iii) it is optimal for \emph{every} "
                       r"admissible capacity")
        else:
            verdict = (f"the recommendation $A_{rec[1]}$ ranks first but carries a strictly "
                       f"positive worst-case regret of ${rec_regret:.4f}$, so it is not optimal "
                       r"for every admissible capacity")
        open(os.path.join(out_dir, f"tab_mcr_{case}.tex"), "w").write(
            tex_table(m, f"Choquet scores and maximum coalitional regret for {nm}.",
                      f"tab:mcr{case}", "l" + "rrrr" + "c",
                      note=(f"Computed at the uncertainty radius "
                            f"$\\varepsilon={digest['epsilon']:.2f}$; the certified stability "
                            f"radius is $\\varepsilon^{{\\star}}_{{\\infty}}="
                            f"{d_['stability_radius_linf']:.4f}$. Here {verdict}."
                            # only explain the dash in the case where one is printed
                            + (" A dash marks an alternative with no binding adversary, "
                               "i.e. one whose regret is attained by no challenger."
                               if has_dash else ""))))

        # ---- comparator ranks -----------------------------------------------
        # TRANSPOSED relative to the natural pivot: with eleven comparators as columns
        # the table is far wider than the text block and the right-hand columns are
        # pushed off the page. Methods therefore become rows and postures columns.
        b = pd.read_csv(os.path.join(results, f"benchmarks_{case}.csv"))
        piv = b.pivot(index="method", columns="posture", values="rank")[POST]
        piv.columns = [f"$A_{p[1]}$" for p in piv.columns]
        order = [mm for mm in [
            "SSR-MCDA (Choquet score)", "SSR-MCDA (minimax regret)",
            "Choquet (Marichal-Roubens capacity)", "WSM (Shapley weights)",
            "WSM (entropy weights)", "WSM (CRITIC weights)", "WSM (BWM weights)",
            "TOPSIS (Shapley weights)", "VIKOR (Shapley weights, Q)",
            "PROMETHEE II (Shapley weights)", "COPRAS (Shapley weights)",
            "SMAA-2 (rank-1 acceptability)"] if mm in piv.index]
        piv = piv.loc[order + [i for i in piv.index if i not in order]]
        piv.index = [(mm.replace("SSR-MCDA", "SSR")
                        .replace("Marichal-Roubens", "Marichal--Roubens")
                        .replace(" (Shapley weights, Q)", r" ($\varphi$, $Q$)")
                        .replace(" (Shapley weights)", r" ($\varphi$)")
                        .replace(" (entropy weights)", " (entropy)")
                        .replace(" (CRITIC weights)", " (CRITIC)")
                        .replace(" (BWM weights)", " (BWM)")
                        .replace(" (rank-1 acceptability)", " (rank-1 acc.)"))
                     for mm in piv.index]
        piv.index.name = "Method"
        open(os.path.join(out_dir, f"tab_bench_{case}.tex"), "w").write(
            tex_table(piv.astype(int),
                      f"Ranks produced by SSR-MCDA and the comparator procedures for {nm}. "
                      f"Rank 1 is best. Methods are rows and postures columns so that all "
                      f"comparators fit within the text width.",
                      f"tab:bench{case}", "l" + "c" * piv.shape[1], float_fmt="%d",
                      note=(r"$\varphi$ marks a method run on the identified Shapley "
                            r"importance vector. The Marichal--Roubens row is a 2-additive "
                            r"Choquet model identified from the \emph{same} revealed "
                            r"preferences by maximum separation, and is the comparator that "
                            r"isolates what the discrimination game contributes.")))

    # T9 revealed preferences
    rows = []
    for case in CASES:
        for a, bb, j in REVEALED_PREFERENCES[case]:
            rows.append({"Economy": "United States" if case == "USA" else "India",
                         "Statement": f"$A_{a[1]} \\succsim A_{bb[1]}$",
                         "Documented policy basis": j})
    open(os.path.join(out_dir, "tab_prefs.tex"), "w").write(
        tex_table(pd.DataFrame(rows),
                  "The revealed-preference set $\\Pi$. Each statement is grounded in an "
                  "observed policy action rather than in a questionnaire response.",
                  "tab:prefs", "llp{9.2cm}", index=False))

    # T10 data sources
    src = pd.DataFrame([
        {"Input": "Applied MFN tariffs, HS-6", "Source": "UNCTAD-TRAINS via the World Bank WITS SDMX API",
         "Coverage": "12 reporters, 8 HS-6 lines, 2018 / 2022 / 2023"},
        {"Input": "Bilateral merchandise imports", "Source": "WITS TradeStats, indicator MPRT-TRD-VL",
         "Coverage": "5 reporters, 5 product groups, 2018 / 2022 / 2023"},
        {"Input": "Bilateral merchandise exports", "Source": "WITS TradeStats, indicator XPRT-TRD-VL",
         "Coverage": "United States and India, 2022"},
        {"Input": "Logistics Performance Index", "Source": "World Bank WDI, LP.LPI.OVRL.XQ", "Coverage": "2022"},
        {"Input": "Tariff, trade and manufacturing aggregates", "Source": "World Bank WDI (9 indicators)",
         "Coverage": "14 economies, 2015--2024"},
        {"Input": "Geopolitical alignment", "Source": "UNGA ideal-point alignment scores, Airaudo et al. (2025)",
         "Coverage": "14 economies, 2021 and 2023"},
        {"Input": "Great-circle distance", "Source": "Capital-city coordinates, haversine formula",
         "Coverage": "15 capitals"}])
    open(os.path.join(out_dir, "tab_sources.tex"), "w").write(
        tex_table(src, "Data sources. Every model input except the declared calibration "
                       "parameter $\\delta_{\\mathrm{DOM}}$ is an observation retrieved "
                       "programmatically; the retrieval logs are part of the replication package.",
                  "tab:sources", "lp{5.6cm}p{4.6cm}", index=False))

    # T11 literature gap
    gap = pd.DataFrame([
        {"Stream": "Choquet-integral MCDA and capacity identification",
         "Representative work": "Grabisch (1996); Grabisch et al. (2008); Mayag and Bouyssou (2020)",
         "What is missing": "capacities are elicited or fitted; none is generated by a strategic model"},
        {"Stream": "Cooperative solution concepts in operations",
         "Representative work": "Luo et al. (2022); Meng et al. (2023)",
         "What is missing": "Shapley value used to allocate cost or reach consensus, never to weight criteria"},
        {"Stream": "Robust ranking and acceptability analysis",
         "Representative work": "Greco et al. (2008, 2014); Lahdelma and Salminen (2001)",
         "What is missing": "robustness explored by sampling or by compatible sets; no certified radius"},
        {"Stream": "Stackelberg and bilevel pricing",
         "Representative work": "van Hoesel (2008); Labb\\'e and Violin (2016)",
         "What is missing": "single-objective; equilibrium never feeds a multi-criteria evaluation"},
        {"Stream": "Tariffs and supply-chain configuration",
         "Representative work": "Dong and Kouvelis (2020); Freund et al. (2024)",
         "What is missing": "optimises one economic objective; no stakeholder plurality"},
        {"Stream": "MCDA applied to trade and sourcing",
         "Representative work": "Sequeira et al. (2023); Wang et al. (2024); G\\\"urler et al. (2024)",
         "What is missing": "decision matrix assumed exogenous and weights elicited from experts"}])
    open(os.path.join(out_dir, "tab_gap.tex"), "w").write(
        tex_table(gap, "Positioning against the six literature streams the paper joins.",
                  "tab:gap", "p{3.5cm}p{4.6cm}p{5.6cm}", index=False))
    print(f"wrote 11+ tables to {out_dir}")


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default=os.path.normpath(os.path.join(here, "..", "results")))
    ap.add_argument("--out", default=os.path.normpath(os.path.join(here, "..", "manuscript")))
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    txt = build_numbers(a.results)
    open(os.path.join(a.out, "numbers.tex"), "w").write(txt)
    print(f"wrote {txt.count(chr(10))} lines to numbers.tex")
    build_tables(a.results, os.path.join(a.out, "tables"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
