#!/usr/bin/env python3
"""

Usage:  python make_seps.py [--manuscript ../manuscript]

Author: Saptadeep Biswas
"""

from __future__ import annotations

import argparse
import os
import re

SUBS = [
    (r"\\documentclass\[preprint,authoryear,3p,times\]\{elsarticle\}",
     r"\\documentclass[preprint,number,sort&compress,3p,times]{elsarticle}"),
     r"\\journal{Socio-Economic Planning Sciences}"),
    (r"\\bibliographystyle\{elsarticle-harv\}",
     r"\\bibliographystyle{elsarticle-num-names}"),
]

BANNER = (
    "%=======================================================================\n"
    "%  AUTO-GENERATED by code/make_seps.py from main.tex -- DO NOT EDIT.\n"
    "%  Socio-Economic Planning Sciences variant (numbered references).\n"
    "%  Article type at submission: 'VSI: MCDA for Tariffs and Supply Chains'.\n"
    "%  Edit main.tex and re-run make_seps.py instead.\n"
    "%=======================================================================\n"
)


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--manuscript",
                    default=os.path.normpath(os.path.join(here, "..", "manuscript")))
    a = ap.parse_args()
    src = os.path.join(a.manuscript, "main.tex")
    dst = os.path.join(a.manuscript, "main_seps.tex")
    text = open(src).read()
    applied = 0
    for pat, rep in SUBS:
        text, k = re.subn(pat, rep, text, count=1)
        applied += k
        if k == 0:
            raise SystemExit(f"make_seps: pattern not found -> {pat}")
    open(dst, "w").write(BANNER + text)
    print(f"wrote {dst} ({applied}/{len(SUBS)} substitutions applied)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
